apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: incibe-r01-svsm-app
  description: SVSM main website
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/DDC-NEORIS/incibe-r01-svsm-app/blob/main/README.md
    backstage.io/source-location: url:https://github.com/DDC-NEORIS/incibe-r01-svsm-app/src/main/
    sonarqube.org/project-key: incibe-svsm_svsm # YOUR_PROJECT_KEY
    bitbucket.org/repository-slug: 'svsm/incibe-r01-svsm-app' # {workspace_slug}/{repo_slug}
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: all
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=svsm'
    backstage.io/kubernetes-namespace: 'svsm'
    dev.azure.com/project-repo: 'incibe-r01-svsm-app/incibe-r01-svsm-app'
    github.com/project-slug: 'DDC-NEORIS/incibe-r01-svsm-app'
    # backstage.io/kubernetes-id: dso-backstage
    circleci.com/project-slug: bitbucket/svsm/incibe-r01-svsm-app
    grafana/overview-dashboard: 'https://grafana.aws.neoris.cloud/d/cluster-costs/cluster-cost-and-utilization-metrics?orgId=1&refresh=15m&viewPanel=116&kiosk=true'
    jenkins.io/job-full-name: 'svsm'
    gitlab.com/project-slug: anpeni/incibe-r01-svsm-app
    tektonci/build-namespace: 'svsm'
  tags:
    - react
    - nodejs
  links:
    # - url: https://backstage-stg.aws.neoris.cloud/
    #   title: Web dev
    # icon: code
    - url: https://github.com/DDC-NEORIS/incibe-r01-svsm-app
      title: GitHub Repo
      icon: Github
    - url: https://github.com/DDC-NEORIS/incibe-r01-svsm-app-tests
      title: GitHub Testing
      icon: Github
spec:
  type: demo
  lifecycle: production
  system: testops
  owner: neoris
